name: Check Last Commit

on:
  pull_request:
    branches-ignore:
      - master
      - release
      - qa
      - dev

jobs:
  check-last-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Get Head Commit Message
        id: get_head_commit_message
        run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"

        - name: Get Head Previous Commit
        id: get_head_previous_commit
        run: echo "PREVIOUS_COMMIT=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"

      - name: Compare commits
        run: |
          if [ "${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}" == "test-complete:${{ steps.get_head_previous_commit.outputs.PREVIOUS_COMMIT }}" ]; then
            echo "Last commit in the file matches the last commit in the PR branch."
            exit 0
          else
            echo "Last commit in the file does not match the last commit in the PR branch."
            exit 1
          fi
